# Generated by Django 3.0.5 on 2020-07-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default title', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('contents', models.TextField(default='default text')),
            ],
        ),
    ]
